/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab10_group4_assignment2;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Scanner;

public class App {


    public static String homePage(){
        System.out.println("Welcome to Virtual Scroll Access System");
        System.out.println("What can I help you?");
        System.out.println("1.Admin login");
        System.out.println("2.User login");
        System.out.println("3.Guest user");
        System.out.println(("4.Exit"));
        Scanner s = new Scanner(System.in);
        String option = s.nextLine();
//        System.out.println("Your option is "+option);
        return option;
//        AdminPage ap= new AdminPage();
//        ap.adminLogin();
    }
    public static void runApp() throws IOException {
        while (true) {
            String option = homePage();
            if (option.equals("1")) {
                AdminPage ap = new AdminPage();
                ap.adminLoginPage();

            } else if (option.equals("2")) {
                UserPage userpage = new UserPage();
                userpage.initialUserInterface();
            } else if (option.equals("3")) {
                UserPage userpage = new UserPage();
                userpage.GuestUserPage();
            } else if (option.equals("4")) {
                System.out.println("Goodbye");
                break;
            } else {
                //error input handle
            }
        }
    }
    public static void main(String[] args) throws IOException {
        runApp();
    }
}
