/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab10_group4_assignment2;

import org.junit.jupiter.api.BeforeEach;

import java.util.NoSuchElementException;
import java.util.Scanner;
import org.junit.jupiter.api.Test;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;


public class AppTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;
    private final InputStream originalIn = System.in;
    private App app;
    @BeforeEach
    void setUp(){
        app = new App();
        System.setOut(originalOut);
        System.setIn(originalIn);
    }
    @Test
    public void runAppAndexit() throws IOException {
        String simulatedInput = "4\n";
        InputStream inputStream = new ByteArrayInputStream(simulatedInput.getBytes());
        System.setIn(inputStream);
        System.setOut(new PrintStream(outContent));
        app.runApp();
        String expectedOutput ="Welcome to Virtual Scroll Access System\n" +
                "What can I help you?\n" +
                "1.Admin login\n" +
                "2.User login\n" +
                "3.Guest user\n" +
                "4.Exit\n" +
                "Goodbye\n";
        assertEquals(expectedOutput,outContent.toString());
        assertTrue(outContent.toString().contains("4.Exit"));
    }
    @Test
    public void appOption1test(){
        String simulatedInput = "1\n1\n1\n7\n4\n";
        InputStream inputStream = new ByteArrayInputStream(simulatedInput.getBytes());
        System.setIn(inputStream);
        System.setOut(new PrintStream(outContent));

        assertThrows(NoSuchElementException.class, () -> {
            // 调用你期望抛出异常的方法
            app.runApp();
        });

    }
    @Test
    public void appOption2test(){
        String simulatedInput = "2\n2\n";
        InputStream inputStream = new ByteArrayInputStream(simulatedInput.getBytes());
        System.setIn(inputStream);
        System.setOut(new PrintStream(outContent));

        assertThrows(NoSuchElementException.class, () -> {
            // 调用你期望抛出异常的方法
            app.runApp();
        });

    }
    @Test
    public void appOption3test(){
        String simulatedInput = "3\n3\n";
        InputStream inputStream = new ByteArrayInputStream(simulatedInput.getBytes());
        System.setIn(inputStream);
        System.setOut(new PrintStream(outContent));

        assertThrows(NoSuchElementException.class, () -> {
            // 调用你期望抛出异常的方法
            app.runApp();
        });

    }
}
